[package]
name = "p256"
version = "0.1.0"
edition = "2021"

[dependencies]
ckb-std = "0.17.0"
p256 = { version = "0.13.2", default-features = false, features = ["arithmetic", "ecdsa", "alloc"] }

[dev-dependencies]
ckb-testtool = "0.15.0"
serde_json = "1.0"
