name: develop

on:
  pull_request:
  push:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Make
        run: |
          docker run --rm -v `pwd`:/code nervos/ckb-riscv-gnu-toolchain:bionic-20210804 cp -r /riscv /code/riscv
          export PATH="$PATH:`pwd`/riscv/bin" && make all
      - name: Install qemu
        run: |
          sudo apt -y update
          sudo apt -y install qemu-user
      - name: Install ckb-vm
        run: |
          git clone https://github.com/nervosnetwork/ckb-vm
          cd ckb-vm
          cargo build --features=asm --release --example=ckb-vm-runner
      - name: Test
        run: |
          time qemu-riscv64 build/secp256k1_bench_loop 033f8cf9c4d51a33206a6c1c6b27d2cc5129daa19dbd1fc148d395284f6b26411f 304402203679d909f43f073c7c1dcf8468a485090589079ee834e6eed92fea9b09b06a2402201e46f1075afa18f306715e7db87493e7b7e779569aa13c64ab3d09980b3560a3 foo bar
          time ckb-vm/target/release/examples/ckb-vm-runner build/secp256k1_bench_loop main 033f8cf9c4d51a33206a6c1c6b27d2cc5129daa19dbd1fc148d395284f6b26411f 304402203679d909f43f073c7c1dcf8468a485090589079ee834e6eed92fea9b09b06a2402201e46f1075afa18f306715e7db87493e7b7e779569aa13c64ab3d09980b3560a3 foo bar
