name: Develop

on:
  release:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Setup
      run: |
        clang --version
        sudo ln -s $(which llvm-ar-18) /usr/bin/llvm-ar || true
        sudo ln -s $(which llvm-objcopy-18) /usr/bin/llvm-objcopy || true
        rustup target add riscv64imac-unknown-none-elf
    - name: Build
      run: |
        make build
    - name: Bench
      run: |
        cargo install ckb-debugger
        tar zcvf binary.tar.gz binary
        make report >> report.txt
    - name: Store
      uses: softprops/action-gh-release@v2
      with:
        files: |
          binary.tar.gz
          report.txt
